name: Check and Test Python Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: python cache set up
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-py-cache

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: run pytest
        run: |
          pip install pytest
          cp src/rememberthemilk.toml.example src/rememberthemilk.toml
          pytest
